export default {
  Students: [
    {
      ProfileImageURL: "https://i.picsum.photos/id/1005/5760/3840.jpg",
      RegistrationNo: "GRO-1234-kel56",
      RegistrationDate: "14/12/2018",
      RollNo: "ABC-456230",
      Name: "Farrukh",
      FatherName: "Father of Farrukh",
      FatherNIC: "11111-5555555-888",
      ContactNo: "",
      Email: "Email@gamil.com",
      DOB: "",
      BloodGroup: "",
      PermanentAddress: "",
      CurrentAddress: "",
      CurrentClass: "5th",
      Gender: "",
      Documents: [],
      StudentHistory: [
        {
          SchoolName: "Fg Public School",
          SchoolAdress: "Near Fawara chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near Gun chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
      ],
      Comments:
        "trhkbrgbjrh dsjhbdjsbdsubduws euywbubyuyywd uwebweuybweuybwe wedudbyudbwuydbwuydwbqon qubsyggyuwg weubasnnqubq wedhgsjhbqqwhugwqg qbddh uewubewwenlqbhjqbuy eubewbweuwehb",
    },
    {
      ProfileImageURL: "https://i.picsum.photos/id/1/5616/3744.jpg",
      RegistrationNo: "GRO-1234-kel56",
      RegistrationDate: "14/12/2018",
      RollNo: "ABC-456230",
      Name: "Farrukh",
      FatherName: "Father of Farrukh",
      FatherNIC: "11111-5555555-888",
      ContactNo: "",
      Email: "",
      DOB: "",
      BloodGroup: "",
      PermanentAddress: "",
      CurrentAddress: "",
      CurrentClass: "",
      Gender: "",
      Documents: [],
      StudentHistory: [
        {
          SchoolName: "Fg Public School",
          SchoolAdress: "Near Fawara chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near Gun chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
      ],
      Comments: "",
    },
    {
      ProfileImageURL: "http://lorempixel.com/100/100/",
      RegistrationNo: "GRO-1234-kel56",
      RegistrationDate: "14/12/2018",
      RollNo: "ABC-456230",
      Name: "Farrukh",
      FatherName: "Father of Farrukh",
      FatherNIC: "11111-5555555-888",
      ContactNo: "",
      Email: "",
      DOB: "",
      BloodGroup: "",
      PermanentAddress: "",
      CurrentAddress: "",
      CurrentClass: "",
      Gender: "",
      Documents: [],
      StudentHistory: [
        {
          SchoolName: "Fg Public School",
          SchoolAdress: "Near Fawara chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near Gun chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
      ],
      Comments: "",
    },
    {
      ProfileImageURL: "http://lorempixel.com/100/100/",
      RegistrationNo: "GRO-1234-kel56",
      RegistrationDate: "14/12/2018",
      RollNo: "ABC-456230",
      Name: "Farrukh",
      FatherName: "Father of Farrukh",
      FatherNIC: "11111-5555555-888",
      ContactNo: "",
      Email: "",
      DOB: "",
      BloodGroup: "",
      PermanentAddress: "",
      CurrentAddress: "",
      CurrentClass: "",
      Gender: "",
      Documents: [],
      StudentHistory: [
        {
          SchoolName: "Fg Public School",
          SchoolAdress: "Near Fawara chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near Gun chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
      ],
      Comments: "",
    },
    {
      ProfileImageURL: "http://lorempixel.com/100/100/",
      RegistrationNo: "GRO-1234-kel56",
      RegistrationDate: "14/12/2018",
      RollNo: "ABC-456230",
      Name: "Farrukh",
      FatherName: "Father of Farrukh",
      FatherNIC: "11111-5555555-888",
      ContactNo: "",
      Email: "",
      DOB: "",
      BloodGroup: "",
      PermanentAddress: "",
      CurrentAddress: "",
      CurrentClass: "",
      Gender: "",
      Documents: [],
      StudentHistory: [
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near cinema chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
        {
          SchoolName: "Army Public School",
          SchoolAdress: "Near park chowk Attock",
          ClassAdmitted: "3",
          ClassWithdrawl: "7",
          ReasonOfLeaving: "Shifting",
          AdditionalComments: "He reamined a good student all the time.",
        },
      ],
      Comments: "",
    },
  ],
  Classes: [
    {
      class: { id: 1, name: "Nursery" },
      Sections: [
        { id: 1, name: "A" },
        { id: 2, name: "B" },
        { id: 3, name: "C" },
      ],
    },
    {
      class: { id: 2, name: "1" },
      Sections: [
        { id: 1, name: "A" },
        { id: 3, name: "C" },
      ],
    },
  ],
};
